CREATE TABLE account
(
    id                  BIGSERIAL,
    name                VARCHAR(256),
    username            VARCHAR(256) NOT NULL UNIQUE,
    email               VARCHAR(256) NULL UNIQUE,
    mobile_phone        VARCHAR(25) NOT NULL UNIQUE,
    password            VARCHAR(256) NOT NULL,
    gender              VARCHAR(25) NULL,
    city_id             BIGINT NULL REFERENCES city (id),
    nationality         BIGINT NOT NULL REFERENCES country (id),
    marital_status      VARCHAR(25) NULL,
    no_of_dependants	SMALLINT DEFAULT 0,
    dob        		    TIMESTAMP,
    tel_no              VARCHAR(256) NULL,
    rp_no               VARCHAR(256) NULL,
    passport_no         VARCHAR(256) NULL,
    rp_validity         VARCHAR(256) NULL,
    sponsor             VARCHAR(256) NULL,
    status              VARCHAR(256) NULL,
    passport_validity   VARCHAR(256) NULL,
    enabled             BOOLEAN   DEFAULT TRUE,
    expired             BOOLEAN   DEFAULT FALSE,
    locked              BOOLEAN   DEFAULT FALSE,
    credentials_expired BOOLEAN   DEFAULT FALSE,
    last_login          TIMESTAMP,
    created_on          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by          BIGINT,
    updated_on          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by          BIGINT,
    approved            BOOLEAN DEFAULT FALSE,
    x                   BOOLEAN DEFAULT FALSE,

    CONSTRAINT pk_account PRIMARY KEY (id)
);
